const data = {
	COLLECTION: [
		{
			photo: 'http://picsum.photos/200?image=1',
			id: '1',
			name: 'John Doe',
			email: 'johndoe@gmail.com',
			active: true,
			last_login: '2018-08-22 08:38:02',
			password: '',
		},
		{
			photo: 'http://picsum.photos/200?image=10',
			id: '2',
			name: 'Jane Doe',
			email: 'jane@gmail.com',
			active: false,
			last_login: '2018-08-22 08:38:02',
			password: '',
		},
		{
			photo: 'http://picsum.photos/200?image=13',
			id: '3',
			name: 'William Defoe',
			email: 'wdef@gmail.com',
			active: true,
			last_login: '2018-08-22 08:38:02',
			password: '',
		},
	],
};

const schema = [
	{ model: 'photo', type: 'photo', 'photo-type': 'user', label: 'Picture', edit: true, list: false },
	{
		model: 'id',
		type: 'edit',
		label: 'ID',
		list: true,
		edit: false,
		readonly: true,
		search: true,
		sort: true,
	},
	{
		model: 'name',
		type: 'varchar',
		label: 'Name',
		list: true,
		edit: true,
		placeholder: 'Your name',
		required: true,
		search: true,
		sort: true,
	},
	{
		model: 'email',
		type: 'varchar',
		inputType: 'email',
		label: 'E-mail',
		list: true,
		edit: true,
		placeholder: "User's e-mail address",
		search: true,
		sort: true,
	},
	{
		model: 'password',
		type: 'password',
		inputType: 'password',
		label: 'Password',
		min: 6,
		required: true,
		list: false,
		edit: true,
		help: 'Minimum 6 characters',
	},
	{ model: 'active', type: 'checkbox', label: 'Active', list: true, edit: true, sort: true },
	{
		model: 'last_login',
		type: 'varchar',
		label: 'Last Login',
		list: true,
		edit: true,
		readonly: true,
		sort: true,
	},
];

export { data, schema };
